if(EXISTS "/home/nawa/CascadeProjects/MyCppLibraryProject/mycpplibrary_tests[1]_tests.cmake")
  include("/home/nawa/CascadeProjects/MyCppLibraryProject/mycpplibrary_tests[1]_tests.cmake")
else()
  add_test(mycpplibrary_tests_NOT_BUILT mycpplibrary_tests_NOT_BUILT)
endif()
